#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calculator.Resource", IsApplication=true)]

namespace Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040011
			public const int btnAdd = 2130968593;
			
			// aapt resource value: 0x7f040004
			public const int btnClear = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int btnDel = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int btnDivide = 2130968582;
			
			// aapt resource value: 0x7f040016
			public const int btnDot = 2130968598;
			
			// aapt resource value: 0x7f04000a
			public const int btnEight = 2130968586;
			
			// aapt resource value: 0x7f04001a
			public const int btnEqual = 2130968602;
			
			// aapt resource value: 0x7f04000f
			public const int btnFive = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int btnFour = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int btnMultiply = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int btnNine = 2130968587;
			
			// aapt resource value: 0x7f040013
			public const int btnOne = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int btnPercent = 2130968600;
			
			// aapt resource value: 0x7f040009
			public const int btnSeven = 2130968585;
			
			// aapt resource value: 0x7f040010
			public const int btnSix = 2130968592;
			
			// aapt resource value: 0x7f04000c
			public const int btnSubtract = 2130968588;
			
			// aapt resource value: 0x7f040015
			public const int btnThree = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int btnTwo = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int btnZero = 2130968601;
			
			// aapt resource value: 0x7f040001
			public const int editText = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout1 = 2130968579;
			
			// aapt resource value: 0x7f040012
			public const int linearLayout2 = 2130968594;
			
			// aapt resource value: 0x7f040008
			public const int linearLayout3 = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int linearLayout4 = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int linearLayout5 = 2130968599;
			
			// aapt resource value: 0x7f040000
			public const int textView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int txtResult = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
